import { collection, query, where, getDocs, addDoc, Timestamp, doc, getDoc } from 'firebase/firestore';
import { db } from '@/config/firebase';

export async function ensureBreakdownTimesheets(
  plantAssetDocId: string,
  breakdownStartDate: string,
  breakdownEndDate: string | null,
  masterAccountId: string,
  siteId: string,
  currentOperatorId?: string,
  currentOperator?: string
): Promise<void> {
  console.log('[BreakdownTimesheetManager] Ensuring breakdown timesheets', {
    plantAssetDocId,
    breakdownStartDate,
    breakdownEndDate: breakdownEndDate || 'ONGOING',
    masterAccountId,
    siteId
  });

  const endDate = breakdownEndDate || new Date().toISOString().split('T')[0];
  const start = new Date(breakdownStartDate);
  const end = new Date(endDate);

  const timesheetsRef = collection(db, `plantAssets/${plantAssetDocId}/timesheets`);
  
  for (let date = new Date(start); date <= end; date.setDate(date.getDate() + 1)) {
    const dateString = date.toISOString().split('T')[0];
    
    const existingQuery = query(
      timesheetsRef,
      where('date', '==', dateString),
      where('isAdjustment', '!=', true)
    );
    
    const existingSnapshot = await getDocs(existingQuery);
    
    if (existingSnapshot.empty) {
      const breakdownTimesheetData = {
        date: dateString,
        openHours: 0,
        closeHours: 0,
        totalHours: 0,
        operatorName: currentOperator || 'Unknown Operator',
        operatorId: currentOperatorId || '',
        isBreakdown: true,
        breakdownNotes: 'Auto-generated from breakdown period',
        breakdownLoggedBy: 'System',
        breakdownLoggedByUserId: 'system',
        breakdownLoggedAt: Timestamp.now(),
        isRainDay: false,
        isStrikeDay: false,
        hasAttachment: false,
        inclementWeather: false,
        scheduledMaintenance: false,
        verified: false,
        createdAt: Timestamp.now(),
        masterAccountId,
        siteId,
        plantAssetDocId,
        autoGenerated: true
      };

      await addDoc(timesheetsRef, breakdownTimesheetData);
      console.log(`[BreakdownTimesheetManager] Created breakdown timesheet for ${dateString}`);
    } else {
      console.log(`[BreakdownTimesheetManager] Timesheet already exists for ${dateString}`);
    }
  }
  
  console.log('[BreakdownTimesheetManager] Breakdown timesheets ensured');
}

export async function getActiveBreakdownPeriod(
  plantAssetDocId: string
): Promise<{ isOnBreakdown: boolean; startDate: string | null; endDate: string | null }> {
  try {
    const plantAssetRef = doc(db, 'plantAssets', plantAssetDocId);
    const plantAssetSnapshot = await getDoc(plantAssetRef);
    
    if (!plantAssetSnapshot.exists()) {
      return { isOnBreakdown: false, startDate: null, endDate: null };
    }
    
    const data = plantAssetSnapshot.data();
    
    return {
      isOnBreakdown: data.breakdownStatus === true,
      startDate: data.breakdownStartDate || null,
      endDate: data.breakdownEndDate || null
    };
  } catch (error) {
    console.error('[BreakdownTimesheetManager] Error getting breakdown period:', error);
    return { isOnBreakdown: false, startDate: null, endDate: null };
  }
}

export async function isTodayInBreakdownPeriod(
  breakdownStartDate: string | null,
  breakdownEndDate: string | null
): Promise<boolean> {
  if (!breakdownStartDate) return false;
  
  const today = new Date().toISOString().split('T')[0];
  const start = new Date(breakdownStartDate);
  const todayDate = new Date(today);
  
  if (breakdownEndDate) {
    const end = new Date(breakdownEndDate);
    return todayDate >= start && todayDate <= end;
  }
  
  return todayDate >= start;
}
